export enum UserTier {
  FREE = "FREE",
  PREMIUM = "PREMIUM",
}

export enum RateLimitType {
  FIXED_WINDOW = "FIXED_WINDOW",
  SLIDING_WINDOW = "SLIDING_WINDOW",
  TOKEN_BUCKET = "TOKEN_BUCKET",
  SLIDING_WINDOW_COUNTER = "SLIDING_WINDOW_COUNTER",
}
